#!/bin/sh

# pacxx-sync-repo [submodule toplevel]
#
# syncronize the repositories in /cache with the CI settings in
# $CI_REPOSITORY_URL, $CI_COMMIT_REF_NAME, and $CI_COMMIT_SHA.
#
# If submodule is not given, then this CI run was invoked for the toplevel
# pacxx-llvm repo.  Sync that and set if to the given ref/sha, then sync all
# registered submodules.
#
# If submodule is given, then this CI run was invoked for a submodule.  The
# submodule parameter denotes a the path of the submodule within the toplevel
# pacxx-llvm worktree.  The toplevel parameter specifies the url of the
# toplevel pacxx-llvm repo to check out.  It is taken relative to
# $CI_REPOSITORY_URL, but may also be an absolute url.
#
# Sync the toplevel repo.  Attempt to put it on $CI_COMMIT_REF_NAME, or
# failing that on master.  Then sync all registered submodules and set the to
# $CI_COMMIT_REF_NAME, leaving them on whatever the topleve repo specified if
# that fails.  Finally, sync (or clone) the named submodule, and set it to the
# given ref/sha.
#
# Finally, sync the samples repository to the url in $SAMPLES_GIT, defaulting
# to https://github.com/pacxx/samples.git.  Again, try to check it out to
# $CI_COMMIT_REF_NAME, but leave it on master if that fails.

set -ex

toplevel_url=$CI_REPOSITORY_URL$1

cd /cache
repo init -u $toplevel_url
repo sync
repo start master
repo start $CI_COMMIT_REF_NAME

# sync samples
: ${SAMPLES_GIT:=https://github.com/pacxx/samples.git}
sync_to_master "${SAMPLES_GIT}" samples
cd samples
eval "$try_checkout_cmd"
