#!/bin/sh

set -ex

mkdir -p builds/llvm
cd builds/llvm
cmake /cache/pacxx/llvm                                 \
    -DCMAKE_BUILD_TYPE=Release                          \
    -DBUILD_SHARED_LIBS=ON                              \
    -DLLVM_ENABLE_RTTI=ON                               \
    -DLLVM_ENABLE_CXX1Y=ON                              \
    -DCMAKE_BUILD_TYPE=Release                          \
    -DCMAKE_CXX_FLAGS_RELEASE="-O3"                     \
    -DCMAKE_INSTALL_PREFIX="${CI_PROJECT_DIR}/install"

make -j"$(nproc)" install

cd "${CI_PROJECT_DIR}"

mkdir -p builds/barrier
cd builds/barrier
cmake /cache/samples/barrier                                            \
    -DCMAKE_CXX_COMPILER="${CI_PROJECT_DIR}/install/bin/clang++"        \
    -DCMAKE_C_COMPILER="${CI_PROJECT_DIR}/install/bin/clang"            \
    -DCMAKE_BUILD_TYPE=Release                                          \
    -DCMAKE_CXX_FLAGS_RELEASE="-O0 -g"                                  \
    -DPACXX_DIR="${CI_PROJECT_DIR}/install"                             \
    -DCMAKE_MODULE_PATH="${CI_PROJECT_DIR}/install/lib/cmake/pacxx"

make -j"$(nproc)"

LD_LIBRARY_PATH="${CI_PROJECT_DIR}/install/lib" ./barrier
